spring:
  profiles:
    active: dev

  cloud:
    gateway:
      routes:
        - id: path_route
          # uri中的地址可以是其他项目，但是必须在注册中心（比如nacos）中
          uri: lb://product-center
          predicates:
            - Path=/hello/**

server:
  port: 8088
